GET http://localhost:8080/api/product

###

POST http://localhost:8080/api/product
Content-Type: application/json

{
  "product":{"producer":"Asus","model":"zenbook","year":"2018","specs":"super fancy quad core","condition":0,"type":0},"receipt":{"store":"Elkjøp","price":29999,"dateOfPurchase":"2020-02-02T23:00:00.000Z"},"priceCurve":0,"owners":[{"fullName":"Per Persen","from":"2020-02-02T23:00:00.000Z"}]
}

###

POST http://localhost:8080/api/product
Content-Type: application/json

{
  "name": "my mac",
  "price": 1000,
  "type": "PC"
}

###

DELETE http://localhost:8080/api/product/7a957680-2e45-4944-8b97-4ee3b2b6c6a1

###

GET http://localhost:8080/api/product?name=my%20mac

